import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Header from "~/components/Header";
import Hero from "~/components/landing/Hero";
import Features from "~/components/landing/Features";
import { SecondaryFeatures } from "~/components/landing/SecondaryFeatures";
import CallToActionBar from "~/components/landing/CallToActionBar";
import EarnExamples from "~/components/landing/EarnExamples";
import Subscriptions from "~/components/landing/Subscriptions";
import FAQ from "~/components/landing/FAQ";
import Footer from "~/components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ALPHA RESCUE</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Hero />
        <div id="products">
          <Features />
        </div>
        <div id="advantages">
          <SecondaryFeatures />
        </div>
        <CallToActionBar />
        <div id="earn-examples">
          <EarnExamples />
        </div>
        <div id="subscriptions">
          <Subscriptions />
        </div>
        <div id="faq">
          <FAQ />
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Home;
