import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Header from "~/components/landing/Header";
import Hero from "~/components/landing/Hero";
import Features from "~/components/landing/Features";
import { SecondaryFeatures } from "~/components/landing/SecondaryFeatures";
import CallToActionBar from "~/components/landing/CallToActionBar";
import EarnExamples from "~/components/landing/EarnExamples";
import Subscriptions from "~/components/landing/Subscriptions";
import FAQ from "~/components/landing/FAQ";
import Footer from "~/components/landing/Footer";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <Hero />
        <Features />
        <SecondaryFeatures />
        <CallToActionBar />
        <EarnExamples />
        <Subscriptions />
        <FAQ />
        <Footer />
      </main>
    </>
  );
};

export default Home;
