export const raffles = [
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../../pp.jpg",
    benner: "../../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    requirements: [
      {
        platform: "twitter",
        action: "Follow",
        specification: "@0xDEGEN, @RESCUE",
      },
      {
        platform: "metamask",
        action: "Hold",
        specification: "0.5 ETH",
      },
      {
        platform: "discord",
        action: "Join",
        specification: "GENESIS DISCORD, MEMBER ROLE",
      },
    ],
  },
];
