export const raffles = [
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
  {
    id: "falskjdflkajdhfljsf",
    platform: "premint",
    profilePicture: "../../pp.jpg",
    benner: "../../banner.jpg",
    name: "A fundamental dispute",
    author: "AFundamentalDispute",
    isFavorite: false,
    hold: 0,
    subs: 66000,
    deadline: "10/06/2003",
    links: {
      metamask: "twitch.tv/byxirski",
      discord: "twitch.tv/byxirski",
      twitter: "twitch.tv/byxirski",
      nft: "twitch.tv/byxirski",
    },
  },
];
